#!/usr/bin/env bash

SCRIPTNAME=$(basename $0)
FINDTYPEOPTIONS=()
FINDTYPE=''
SEARCHCONTENT=false
DISPLAYINVIM=false
ARGUMENTS=()
NUMBEROFERRORS=0


setOption()
{
    local option=$1

    case ${option} in
        c ) SEARCHCONTENT=true ;;
        d ) FINDTYPEOPTIONS+=('d') ;;
        f ) FINDTYPEOPTIONS+=('f') ;;
        v ) DISPLAYINVIM=true ;;
    esac
}

isValidOption()
{
    local option=$1

    if [ "${option}" = '?' ]
    then
        return 1
    else
        return 0
    fi
}

parseCommandLineOptions()
{
    local getoptsValidOptions=':cdfv'
    local options=$@

    while getopts ${getoptsValidOptions} option ${options}
    do
        if ! isValidOption "${option}"
        then
            ((NUMBEROFERRORS++))
            echo "${SCRIPTNAME}: invalid option '${OPTARG}'" 1>&2
        else
            setOption "${option}"
        fi
    done

    FINDTYPE="-type "$(echo ${FINDTYPEOPTIONS[@]} | tr ' ' ',')
}


parseCommandLineArguments()
{
    while [ $# -gt 0 ]
    do
        parseCommandLineOptions $@

        shift $(($OPTIND - 1))
        unset OPTIND

        if [ $# -gt 0 ]
        then
            ARGUMENTS+=("$1")
            shift
        fi
    done

    return ${NUMBEROFERRORS}
}

validateArguments()
{
    if [ ${#ARGUMENTS[@]} -eq 0 ]
    then
        echo "${SCRIPTNAME}: Usage: ${SCRIPTNAME} [-v] [-c -d -f] NAME"
        return 1
    else
        return 0
    fi
}

displayResult()
{
    local searchPattern="$1"

    local vimExecutable=$(which vim)
    if ${DISPLAYINVIM} && [ ! -z "${vimExecutable}" ]
    then
        local closeVimIfNothingFound='exe !search(".")?"quit!":""'
        local loadExplorerPlugin=':packadd kitty'
        local defineSearchPattern=":let kittysearchpattern = \"${searchPattern}\""
        local moveToFirstSearchResult=':call KittyGoToNextSearchResult()'
        ${vimExecutable} +"${closeVimIfNothingFound}" +"${loadExplorerPlugin}" "+${defineSearchPattern}" "+${moveToFirstSearchResult}" - --not-a-term
    else
        cat
    fi
}

searchFileSystem()
{
    local searchPattern="$1"

    local colorOption='--color=always'
    if ${DISPLAYINVIM} && [ ! -z "$(which vim)" ]
    then
        colorOption=''
    fi

    if ${SEARCHCONTENT}
    then
        find . -not -path '*/\.*' -type f -exec grep ${colorOption} -nHEs -C 1 ".*${searchPattern}.*" '{}' + | displayResult ${searchPattern}
    else
        find . -not -path '*/\.*' ${FINDTYPE} -name "*${searchPattern}*" | displayResult ${searchPattern}
    fi
}


parseCommandLineArguments $@
if [ $? -gt 0 ]
then
    exit 1
fi

validateArguments
if [ $? -gt 0 ]
then
    exit 1
fi

searchFileSystem "${ARGUMENTS[0]}"
