name: Deployment tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package test
        run: ./bazelisk build @kitty//:Release
      - name: Installation test
        run: ./bazelisk test @kitty//tests:InstallationTest
