name: Deployment tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package test
        run: ./bazelisk build @kitty//package:KittyRelease
      - name: Installation test
        run: cd bazel-bin/package && tar -xzf kitty-*.tar.gz && cd kitty-*/ && ./install-kitty.sh
