name: Deployment tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package test
        run: ./bazelisk build @kitty//:KittyRelease
      - name: Installation test
        run: cd bazel-bin && tar -xzf kitty-1.3.tar.gz && cd kitty-1.3/ && ./configure --prefix="$HOME/.local" && make install && mkdir -p $HOME/.vim/pack/plugins/opt/kitty/plugin && cp explorer.vim $HOME/.vim/pack/plugins/opt/kitty/plugin/explorer.vim && cd .. && rm -rf kitty-1.3
