name: System tests

on:
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: System tests
        run: ./bazelisk test @kitty//tests:SystemTests
