name: Code tests

on:
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: System tests
        run: ./bazelisk run @kitty//tests:SystemTests
      - name: Linting (ShellCheck)
        run: ./bazelisk run @kitty//tests:LinterTest
