name: Code tests

on:
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: System tests
        run: ./bazelisk run @kitty//tests:SystemTests
      - name: Lint bash code (ShellCheck)
        run: ./bazelisk run @kitty//tests:LintBashCode
      - name: Lint python test code (Pylint)
        run: |
          pip install pylint
          ./bazelisk run @kitty//tests:LintPythonTestCode
